---
title: "Weight of Fish"
author: "Skye Solis"
date: "Summer 2024"  
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5

 
    
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```

# Predicting Fish Weight

```{r}
Fish <- Fish %>%

mutate(across(where(is.character), as.factor))

levels(Fish$Species)
```


```{r}
Bream <- filter(fish, Species == 

"Bream")

Bream <- select(Bream, -Species) 

Parkki <- filter(fish, Species == 

"Parkki")

Parkki <- select(Parkki, -Species) 

Perch <- filter(fish, Species == 

"Perch")

Perch <- select(Perch, -Species) 

Pike <- filter(fish, Species == 

"Pike")

Pike <- select(Pike, -Species) 

Roach <- filter(fish, Species == 

"Roach")

Roach <- select(Roach, -Species) 

Smelt <- filter(fish, Species == 

"Smelt")

Smelt <- select(Smelt, -Species) 

Whitefish <- filter(fish, Species == 

"Whitefish")

Whitefish <- select(Whitefish, -Species)

## Perch

### Best Models

### Best Two regressor model


## Pike

### Best Models

### Best Two regressor model

## Roach

### Best Models

### Best Two regressor model

## Final Summary Statements
```